### ISSUE TITLE
Flutter downloader not loading  tasks in ios

### ISSUE THREAD

**Issue by noeljayson** [fluttercommunity/flutter_downloader#787]
After downloading the file the plugin does not load the the tasks .

FlutterDownloader.loadTasks() not loading downloaded tasks or its progress 

  List<DownloadTask>? getTasks = await FlutterDownloader.loadTasks();

it shows empty it works in android but not working in ios.

**Comment by markst** [comment]
@noeljayson did it work on a previous version?

**Comment by noeljayson** [comment]
No it's not working in previous version

**Comment by brunoda6** [comment]
Hi,
![3](https://user-images.githubusercontent.com/52214690/210999312-5599c574-24b2-4dac-bc1b-19bd85d12956.png)
![2](https://user-images.githubusercontent.com/52214690/210999318-6830d4cf-8767-40ad-9293-834e75b5c704.png)
![1](https://user-images.githubusercontent.com/52214690/210999321-3626f042-4afe-459e-afdc-f1cf172f3141.png)

Im with the same problem

**Comment by Memet18** [comment]
Hi,I have the same problem, in iOS

**Comment by noeljayson** [comment]
Is this issue solved in lastest update 
I don't have Mac to test

**Comment by markst** [comment]
Need to dig deeper, but from what I can gather the `sqlite3_open` is failing with the error "unable to open database file" returned from `sqlite3_errmsg`.

https://github.com/fluttercommunity/flutter_downloader/blob/master/ios/Classes/DBManager.m#L101

**Comment by markst** [comment]
```
“download_tasks.sql” couldn’t be moved to “Application Support” because either the former doesn’t exist, or the folder containing the latter doesn’t exist.
```

I think this is due to `NSApplicationSupportDirectory` not existing initially and needs to be created:
```objc
[[NSFileManager defaultManager] createDirectoryAtPath:self.appDirectory withIntermediateDirectories:true attributes:nil error:&error];
```

https://stackoverflow.com/questions/16204988/ios-cant-save-file-to-application-support-folder-but-can-to-documents

**Comment by Memet18** [comment]
> 

yes, solved

**Comment by Memet18** [comment]
> Is this issue solved in lastest update
> I don't have Mac to test
yes, solved

**Comment by noeljayson** [comment]
> > Is this issue solved in lastest update
> > I don't have Mac to test
> 
> @noeljayson yes, solved

No bro i have tested it yesterday it is not loading tasks it is showing empty

**Comment by 781flyingdutchman** [comment]
Hi, I've found the flutter_downloader to be comprehensive, but also a bit buggy, so I wrote a much simpler download package [background_downloader](https://pub.dev/packages/background_downloader). Have a look and see if it serves your needs.

**Comment by lucaantonelli** [comment]
> > > Is this issue solved in lastest update
> > > I don't have Mac to test
> > 
> > 
> > @noeljayson yes, solved
> 
> No bro i have tested it yesterday it is not loading tasks it is showing empty

I found the solution, is a problem in the newer update, they added a variable allowCellular, when doing a FlutterDownloader.enqueue() you need to set it inside mandatory if you use loadTasksWithRawQuery, is probably a missing implementation as for loadTasks it is not needed. So just add `allowCellular: true` and it will work.

**Comment by Memet18** [comment]
> > > > Is this issue solved in lastest update
> > > > I don't have Mac to test
> > > 
> > > 
> > > @noeljayson yes, solved
> > 
> > 
> > No bro i have tested it yesterday it is not loading tasks it is showing empty
> 
> I found the solution, is a problem in the newer update, they added a variable allowCellular, when doing a FlutterDownloader.enqueue() you need to set it inside mandatory if you use loadTasksWithRawQuery, is probably a missing implementation as for loadTasks it is not needed. So just add `allowCellular: true` and it will work.

Didn't quite understand your solution, in the FlutterDownloader.enqueue() constructor, "enable cellular" is set to true by default.

**Comment by lucaantonelli** [comment]
> 

I made a PR to solve the issue: #803 
In the latest update they solved the problem for loadTasks but didn't made the implementation for loadTasksWithRawQuery, I solved by editing my local pub cache for now with the code in the PR.

**Comment by daveshirman** [comment]
@lucaantonelli I don't understand either.  I call `enqueue` and receive an ID, but there are no tasks coming back regardless if I call `loadTasksWithRawQuery` or `loadTasks`.

XCode has console messages saying that the db table couldn't be created/opened.

How did you solve this with version `1.10.1+2`?

**Comment by lucaantonelli** [comment]
> 

Maybe i have confused something. I solved a problem where loadTasksWithRawQuery show an error when called if allowCellular was not set.
About your problem of the tasks table not getting created, is something i have struggled with too in the last week, probably something related with the #728 and #757 where they moved the database from public folder to app folder. I will check if i find a solution, for now in my app i switched to open_filex plugin for opening file, i know this isn't a solution.

**Comment by jackleemeta** [comment]
Same issue.

iOS DB is invalid absolutely on FlutterDownloader ^1.9.1. iOS can't open file download_tasks.sql, the file may never be created successfully.

Problem occurred DB migration before?

**Comment by meshivanshsinghh** [comment]
any update on this? I can still see that loadTasks() returns [] sometimes, and sometimes it returns the value. Why is this disimilarities. I am on version: 
flutter_downloader: ^1.11.5 by the time of pasting this issue. 
![image](https://github.com/fluttercommunity/flutter_downloader/assets/40332106/c568c9ef-ed19-498b-9362-8189fb6006ad)


You can see in my console i mostly get this: 
![image](https://github.com/fluttercommunity/flutter_downloader/assets/40332106/465647b7-8080-4e8b-be76-8fed1593fde9)
